server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: secret
        url: jdbc:mysql://localhost:3306/lending
        username: appuser
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
